//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Shopping_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Reviews = new HashSet<Review>();
        }
    
        public int order_id { get; set; }
        public int seller_id { get; set; }
        public int buyer_id { get; set; }
        public int product_id { get; set; }
        public int category_id { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual tbl_user tbl_user { get; set; }
        public virtual tbl_category tbl_category { get; set; }
        public virtual tbl_product tbl_product { get; set; }
        public virtual tbl_user tbl_user1 { get; set; }
        public virtual tbl_product tbl_product1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
    }
}
