//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Shopping_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int review_id { get; set; }
        public int seller_id { get; set; }
        public int buyer_id { get; set; }
        public int product_id { get; set; }
        public string review_message { get; set; }
        public int order_id { get; set; }
        public int rating { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual tbl_user tbl_user { get; set; }
        public virtual tbl_product tbl_product { get; set; }
        public virtual tbl_user tbl_user1 { get; set; }
    }
}
